/**
 * Groth16 legal-path proof verification panel.
 *
 * Pulls the shipped artifacts (proof + vk + public inputs) and runs
 * our pure-Python verifier. Shows three outcomes:
 *   - honest      : the proof should verify
 *   - tamper_goal : flipping the public goal id breaks the proof
 *   - tamper_adj  : flipping one adjacency bit also breaks the proof
 *
 * Side-by-side check that ZK is BINDING to the public inputs.
 */

import { useEffect, useState } from "react";

interface ZKResult {
  available: boolean;
  reason?: string;
  circuit?: string;
  n_public_inputs?: number;
  honest?: { inputs: number[]; verified: boolean };
  tamper_goal?: { inputs: number[]; verified: boolean };
  tamper_adjacency?: { inputs: number[]; verified: boolean };
}

export function ZKVerifyChart() {
  const [data, setData] = useState<ZKResult | null>(null);
  const [loading, setLoading] = useState(false);

  const run = async () => {
    setLoading(true);
    try {
      const res = await fetch("/crypto/zk/legal-path");
      if (res.ok) setData((await res.json()) as ZKResult);
    } catch {}
    setLoading(false);
  };

  useEffect(() => {
    void run();
  }, []);

  if (!data) {
    return (
      <div className="font-mono text-xs text-[color:var(--color-penumbra-muted)]">
        loading verifier…
      </div>
    );
  }
  if (!data.available) {
    return (
      <div className="font-mono text-xs text-[color:var(--color-penumbra-muted)]">
        {data.reason ?? "circuit artifacts missing"}
      </div>
    );
  }

  return (
    <div className="font-mono space-y-3">
      <div className="grid grid-cols-3 gap-2 text-[10px]">
        <Stat label="circuit" value={data.circuit ?? "—"} />
        <Stat label="public inputs" value={String(data.n_public_inputs ?? 0)} accent />
        <button
          type="button"
          onClick={run}
          disabled={loading}
          className="border border-[color:var(--color-penumbra-cyan)] bg-[color:var(--color-penumbra-cyan-bg)] px-2 py-1 text-[10px] uppercase tracking-wider text-[color:var(--color-penumbra-cyan)] disabled:opacity-50"
        >
          {loading ? "verifying…" : "re-verify"}
        </button>
      </div>

      <Row
        label="honest proof"
        verified={data.honest?.verified ?? false}
        caption="proof + original public inputs"
      />
      <Row
        label="tampered goal"
        verified={data.tamper_goal?.verified ?? false}
        caption="public input goal flipped → should REJECT"
      />
      <Row
        label="tampered adjacency"
        verified={data.tamper_adjacency?.verified ?? false}
        caption="adjacency bit flipped → should REJECT"
      />

      <div className="text-[9px] text-[color:var(--color-penumbra-dim)]">
        verifier = pure-Python Groth16 (py_ecc); proof generated by snarkjs +
        circom legal_path (4-node graph, 2-hop walk).
      </div>
    </div>
  );
}

function Row({
  label,
  verified,
  caption,
}: {
  label: string;
  verified: boolean;
  caption: string;
}) {
  return (
    <div className="flex items-center justify-between border border-[color:var(--color-penumbra-border)] bg-[color:var(--color-penumbra-bg)] px-2 py-2">
      <div>
        <div className="text-[10px] uppercase tracking-wider text-[color:var(--color-penumbra-muted)]">
          {label}
        </div>
        <div className="text-[9px] text-[color:var(--color-penumbra-dim)]">{caption}</div>
      </div>
      <div
        className={
          verified
            ? "border border-[color:var(--color-penumbra-cyan)] bg-[color:var(--color-penumbra-cyan-bg)] px-2 py-0.5 text-[11px] uppercase tracking-wider text-[color:var(--color-penumbra-cyan)]"
            : "border border-[color:var(--color-penumbra-ember)] bg-[color:var(--color-penumbra-ember-bg)] px-2 py-0.5 text-[11px] uppercase tracking-wider text-[color:var(--color-penumbra-ember)]"
        }
      >
        {verified ? "ACCEPT" : "REJECT"}
      </div>
    </div>
  );
}

function Stat({
  label,
  value,
  accent,
}: {
  label: string;
  value: string;
  accent?: boolean;
}) {
  return (
    <div className="border border-[color:var(--color-penumbra-border)] bg-[color:var(--color-penumbra-bg)] px-2 py-1">
      <div className="text-[8px] uppercase tracking-wider text-[color:var(--color-penumbra-dim)]">
        {label}
      </div>
      <div
        className={`tabular-nums ${accent ? "text-[color:var(--color-penumbra-cyan)]" : "text-[color:var(--color-penumbra-text)]"}`}
      >
        {value}
      </div>
    </div>
  );
}
