"""Pedersen commitments — pedagogical implementation.

Concept taught: a commitment scheme is "binding" if the committer can't
open it two different ways, and "hiding" if the verifier learns nothing
about the committed value before opening.

Pedersen: in a prime-order group ⟨g⟩ with auxiliary generator h such
that log_g h is unknown to anyone,

    C(m, r) = g^m · h^r        (with r ←R Z_q chosen by the committer)

is **perfectly hiding** (r is uniform; C is uniform over the group) and
**computationally binding** under the discrete-log assumption (opening
to two pairs (m, r), (m', r') with m ≠ m' would give log_g h).

In Penumbra these underpin Schnorr ZK proofs and stand-ins for any
"reveal later" protocol.

We use a Schnorr group: a prime-order subgroup of Z_p* generated by g
of order q with p = 2q + 1 a safe prime. The group operation is integer
multiplication mod p. Pedagogical clarity > performance — for production
we'd use an elliptic-curve group instead (no compatible py_ecc API for
arbitrary prime-order subgroups, hence the Schnorr group here).
"""

from __future__ import annotations

import secrets
from dataclasses import dataclass
from typing import Final

# A 2048-bit safe prime p = 2q + 1, q prime. Generated once and pinned
# so two test runs share the same group. The generator g has order q;
# h has order q and discrete log to g is unknown.
#
# (The values below are the "MODP Group 14" parameters from RFC 3526,
# §3, widely deployed and adequate for an educational module.)
_P: Final[int] = int(  # noqa: PLR0913 — multi-line hex literal for readability
    "FFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD1"  # pyright: ignore[reportImplicitStringConcatenation]
    "29024E088A67CC74020BBEA63B139B22514A08798E3404DD"
    "EF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245"
    "E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7ED"
    "EE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3D"
    "C2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F"
    "83655D23DCA3AD961C62F356208552BB9ED529077096966D"
    "670C354E4ABC9804F1746C08CA18217C32905E462E36CE3B"
    "E39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9"
    "DE2BCBF6955817183995497CEA956AE515D2261898FA0510"
    "15728E5A8AACAA68FFFFFFFFFFFFFFFF",
    16,
)
_Q: Final[int] = (_P - 1) // 2
_G: Final[int] = 2


# h = g^x for a *publicly-fixed* x chosen by hashing a domain separator.
# In production h would come from a transparent setup (e.g. nothing-up-
# my-sleeve hash to a curve point); here we use SHA-256 of a domain tag
# reduced mod q as the exponent and h = g^x mod p.
def _derive_h() -> int:
    import hashlib

    digest = hashlib.sha256(b"penumbra-pedersen-h-generator").digest()
    x = int.from_bytes(digest, "big") % _Q
    return pow(_G, x, _P)


_H: Final[int] = _derive_h()


@dataclass(frozen=True, slots=True)
class Commitment:
    """A Pedersen commitment value plus a hint of the group it lives in."""

    value: int


@dataclass(frozen=True, slots=True)
class Opening:
    """Witness to open a commitment: the message and the blinding factor."""

    message: int
    blinding: int


def commit(message: int, blinding: int | None = None) -> tuple[Commitment, Opening]:
    """Commit to `message` ∈ Z_q with optional explicit `blinding` (else fresh).

    Returns `(commitment, opening)`. The opening is for the committer to
    retain; the commitment is broadcast.
    """
    if not 0 <= message < _Q:
        raise ValueError("message must lie in Z_q")
    r = blinding if blinding is not None else secrets.randbelow(_Q)
    if not 0 <= r < _Q:
        raise ValueError("blinding must lie in Z_q")
    c_value = (pow(_G, message, _P) * pow(_H, r, _P)) % _P
    return Commitment(value=c_value), Opening(message=message, blinding=r)


def verify(commitment: Commitment, opening: Opening) -> bool:
    """Check whether `opening` produces `commitment` under the group params."""
    expected = (pow(_G, opening.message, _P) * pow(_H, opening.blinding, _P)) % _P
    # Constant-time compare on the integer bytes is overkill here (the
    # commitment is public information by design), but we use it anyway
    # to model the right habit.
    import hmac

    return hmac.compare_digest(expected.to_bytes(256, "big"), commitment.value.to_bytes(256, "big"))


def group_params() -> tuple[int, int, int, int]:
    """Return (p, q, g, h) for callers that need to share the same group."""
    return _P, _Q, _G, _H
